### ISSUE TITLE
How can I add it to my discord server?

### ISSUE THREAD

**Issue by jjanexd** [cryzereye/vouch-bot-js#4]
Hi, how can I add it to my discord server, I still don't know much about this

**Comment by cryzereye** [comment]
Fork this repo, do the usual Discorb bot setup, and create the necessary configs. I will give you a sample template on the configs. Wait for a bit.

**Comment by jjanexd** [comment]
okay thank you

**Comment by cryzereye** [comment]
[json.zip](https://github.com/cryzereye/keebot/files/13997362/json.zip)

Attached contains all JSON files that should be inside `src/json`. The property names are decently named so just follow them. Hit me up again if you have more questions.

**Comment by jjanexd** [comment]
Thank you, i really liked your bot. One last quetion, how does the scorer.js system work, i mean how can i get the points is it any type of command or else? Thank you so much, you are the best.

**Comment by cryzereye** [comment]
There should be a dedicated channel where users can vouch each other. That channel's ID should be in `config.json`'s channelsID.verify.

The rules for scoring are simple:
+1 point to userA if userA mentions userB
+1 point to userB if userB replies to the message userB got mentioned
